#pragma kernel ComputeMoonHeight

// Structured Buffer to hold vertex positions
StructuredBuffer<float3> vertices;

RWStructuredBuffer<float> heights;

uint numVertices;
float testValue;

[numthreads(512, 1, 1)] // Define the number of threads per group
void ComputeMoonHeight(uint id : SV_DispatchThreadID)
{
    if (id >= numVertices) // Prevent out-of-bounds access
        return;

    float3 vertexPos = vertices[id];
    heights[id] = 1 + sin(vertexPos.y * testValue) * 0.05;
}
